spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/member-command/sign-in]':
            allowedOrigins: '*'
            allowedHeaders: '*'
            allowedMethods: 
              - POST
              - OPTIONS
          '[/help-history-query/certificate]':
            allowedOrigins: '*'
            allowedHeaders: '*'
            allowedMethods: 
              - GET
              - OPTIONS
          '[/member-query/]':
            allowedOrigins: '*'
            allowedHeaders: '*'
            allowedMethods: 
              - GET
              - OPTIONS
      routes:
        - id: member-query
          uri: lb://MEMBER-QUERY-SERVICE/
          predicates:
            - Path=/member-query/availability/**,/member-query/public/**
          filters:
            - RewritePath=/member-query/(?<path>.*),/$\{path}
        - id: member-query-authorization
          uri: lb://MEMBER-QUERY-SERVICE/
          predicates:
            - Path=/member-query/
          filters:
            - RewritePath=/member-query/(?<path>.*),/$\{path}
            - AuthorizationHeaderFilter
        - id: member-sync
          uri: lb://MEMBER-SYNC-SERVICE/
          predicates:
            - Path=/member-sync/**
          filters:
            - RewritePath=/member-command/(?<path>.*),/$\{path}
        - id: member-command-authorization
          uri: lb://MEMBER-COMMAND-SERVICE/
          predicates:
            - Path=/member-command/**
            - Method=GET,PUT,DELETE,PATCH
          filters:
            - RewritePath=/member-command/(?<path>.*),/$\{path}
            - AuthorizationHeaderFilter
        - id: member-command
          uri: lb://MEMBER-COMMAND-SERVICE/
          predicates:
            - Path=/member-command/**
            - Method=POST
          filters:
            - RewritePath=/member-command/(?<path>.*),/$\{path}
        - id: monster
          uri: lb://MONSTER-SERVICE/
          predicates:
            - Path=/monster/**
          filters:
            - RewritePath=/monster/(?<path>.*),/$\{path}
            - AuthorizationHeaderFilter
        - id: notification
          uri: lb://NOTIFICATION-SERVICE/
          predicates:
            - Path=/notification/**
          filters:
            - RewritePath=/notification/(?<path>.*),/$\{path}
            - AuthorizationHeaderFilter
        - id: help-history-command
          uri: lb://HELP-HISTORY-COMMAND-SERVICE/
          predicates:
            - Path=/help-history-command/**
          filters:
            - RewritePath=/help-history-command/(?<path>.*),/$\{path}
        - id: help-history-query
          uri: lb://HELP-HISTORY-QUERY-SERVICE/
          predicates:
            - Path=/help-history-query/**
          filters:
            - RewritePath=/help-history-query/(?<path>.*),/$\{path}
            - AuthorizationHeaderFilter
        - id: category
          uri: lb://CATEGORY-SERVICE/
          predicates:
            - Path=/category/default,/category/getCategoryInfo/**
          filters:
            - RewritePath=/category/(?<path>.*),/$\{path}
        - id: category-authorization
          uri: lb://CATEGORY-SERVICE/
          predicates:
            - Path=/category/**
          filters:
            - RewritePath=/category/(?<path>.*),/$\{path}
            - AuthorizationHeaderFilter
        - id: help-match
          uri: lb://HELP-MATCH-SERVICE/
          predicates:
            - Path=/help-match/**
          filters:
            - RewritePath=/help-match/(?<path>.*),/$\{path}
            - AuthorizationHeaderFilter
        - id: help-match-socket
          uri: lb:ws://HELP-MATCH-SERVICE/
          predicates:
            - Path=/help-match-socket/**
          filters:
            - RewritePath=/help-match-socket/(?<path>.*),/$\{path}
        - id: ocr
          uri: lb://OCR-SERVICE/
          predicates:
            - Path=/ocr/**
          filters:
            - RewritePath=/ocr/(?<path>.*),/$\{path}
        - id: chat
          uri: lb:ws://CHAT-SERVICE/
          predicates:
            - Path=/chat/**
          filters:
            - RewritePath=/chat/(?<path>.*),/$\{path}
        - id: member-report
          uri: lb://MEMBER-REPORT-SERVICE/
          predicates:
            - Path=/member-report/**
          filters:
            - RewritePath=/member-report/(?<path>.*),/$\{path}
            - AuthorizationHeaderFilter

        
