export function load({ params }: any) {
    return {
        type: params.type,
        level: params.level,
        type1: [
            {url: '/FennecFox_Animations.glb', name: 'M_FennecFox'},
            {url: '/Rabbit_Animations.glb', name: 'M_Rabbit'},
            {url: '/Dog_Animations.glb', name: 'M_Dog'},
            {url: '/Fox_Animations.glb', name: 'M_Fox'},
            {url: '/Gazelle_Animations.glb', name: 'M_Gazelle'},
            {url: '/Zebra_Animations.glb', name: 'M_Zebra'},
            {url: '/Pig_Animations.glb', name: 'M_Pig'},
            {url: '/Buffalo_Animations.glb', name: 'M_Buffalo'},
            {url: '/Ox_Animations.glb', name: 'M_Ox'},
            {url: '/Elephant_Animations.glb', name: 'M_Elephant'},
        ],
        type2: [
            {url: '/Prawn_Animations.glb', name: 'M_Prawn'},
            {url: '/Catfish_Animations.glb', name: 'M_Catfish'},
            {url: '/Alligator_Animations.glb', name: 'M_Alligator'},
            {url: '/Tuna_Animations.glb', name: 'M_Tuna'},
            {url: '/Tortoise_Animations.glb', name: 'M_Tortoise'},
            {url: '/Turtle_Animations.glb', name: 'M_Turtle'},
            {url: '/Jellyfish_Animations.glb', name: 'M_Jellyfish'},
            {url: '/Walrus_Animations.glb', name: 'M_Walrus'},
            {url: '/SeaLion_Animations.glb', name: 'M_SeaLion'},
            {url: '/RiverDolphin_Animations.glb', name: 'M_RiverDolphin'},
        ],
        type3: [
            {url: '/Chick_Animations.glb', name: 'M_Chick'},
            {url: '/Hen_Animations.glb', name: 'M_Hen'},
            {url: '/Penguin_Animations.glb', name: 'M_Penguin'},
            {url: '/Owl_Animations.glb', name: 'M_Owl'},
            {url: '/Dove_Animations.glb', name: 'M_Dove'},
            {url: '/Macaw_Animations.glb', name: 'M_Macaw'},
            {url: '/Kakapo_Animations.glb', name: 'M_Kakapo'},
            {url: '/Ostrich_Animations.glb', name: 'M_Ostrich'},
            {url: '/Flamingo_Animations.glb', name: 'M_Flamingo'},
            {url: '/Shoebill_Animations.glb', name: 'M_Shoebill'},
        ],
        type4: [
            {url: '/Whale_Animations.glb', name: 'M_Whale'},
        ],
    };
}
