import { StyleSheet } from "react-native"
import { responsiveWidth } from "react-native-responsive-dimensions";

const MainStyle = StyleSheet.create({
    mainWrap:{
        marginHorizontal:responsiveWidth(4),
    },
    mainTitle:{
        fontSize:28,
        fontWeight:"700",
        color:"#3B3F42",
        marginTop:11,
        marginLeft:10,
    },
    pointBlue:{
        color:"#6283D8",
    },
    mainDescription:{
        fontSize:14,
        fontWeight:"500",
        color:"#7D8182",
        marginTop:8,
        marginLeft:10,
    },
    mainImg:{
        width:responsiveWidth(60),
        height:responsiveWidth(60),
        marginLeft:"auto",
        marginRight:"auto",
        marginTop:43,
    },
    helpButton:{
        width:"100%",
        height:50,
        borderRadius:4,
        backgroundColor:"#5287E7",
        display:"flex",
        justifyContent:"center",
        alignItems:"center",
        marginTop:42,
    },
    helpButtonText:{
        fontSize:16,
        fontWeight:"500",
        color:"#FFFFFF",
    },
    signUpText:{
        fontSize:12,
        fontWeight:"500",
        color:"#5287E7",
        textAlign:"center",
        marginTop:8,
    },

    boxWrap:{
        marginHorizontal:responsiveWidth(4),
        marginTop:52,
    },
    boxMainTitle:{
        fontSize:18,
        fontWeight:"700",
        color:"#000000",
    },
    boxSubTitle:{
        fontSize:12,
        fontWeight:"500",
        color:"#ABABAD",
        marginTop:6,
    },
    boxFlexWrap:{
        display:"flex",
        flexDirection:"row",
        justifyContent:"flex-start",
        alignItems:"center",
        borderWidth:1,
        borderColor:"#F4F4F2",
        borderRadius:8,
        marginHorizontal:responsiveWidth(2),
    },
    boxContentWrap:{
        marginTop:14,
        borderWidth:3,
        borderColor:"#ddd",
        borderRadius:10,
        paddingHorizontal:22,
        paddingVertical:28,
        marginHorizontal:responsiveWidth(2),
    },
    boxContentTitle:{
        fontSize:14,
        fontWeight:"700",
        color:"#000000",
    },
    boxContentSubTitle:{
        fontSize:10,
        fontWeight:"500",
        color:"#AFAFAF",
        marginTop:7,
    },
    boxContentImg:{
        width:40,
        height:40,
        marginLeft:"auto",
        marginTop:10,
    },

    happyWrap:{
        marginTop:34,
        backgroundColor:"#F8F8FA",
        paddingHorizontal:responsiveWidth(4),
        paddingVertical:55,
    },
    happyMainTitle:{
        fontSize:18,
        fontWeight:"700",
        color:"#303032",
    },
    happySubTitle:{
        fontSize:14,
        fontWeight:"400",
        color:"#909497",
        marginTop:6,
    },

    moveMypageButton:{
        borderWidth:1,
        borderColor:"#D9D9D9",
        borderRadius:8,
        display:"flex",
        flexDirection:"row",
        alignItems:"center",
        paddingVertical:16,
        marginTop:21,
    },
    cloverImg:{
        width:30,
        height:30,
        marginLeft:17,
    },
    rightArrowIcon:{
        width:14,
        height:14,
        marginLeft:"auto",
        marginRight:21,
    },
    moveMypageTextWrap:{
        marginLeft:15,
    },
    moveMypageTextTitle:{
        fontSize:12,
        fontWeight:"500",
        color:"#5B5B5B",
    },
    moveMypageTextDesc:{
        fontSize:14,
        fontWeight:"700",
        color:"#1F1F1F",
    },
})

export default MainStyle;